import assert from "node:assert/strict";
import test from "node:test";

import { shouldAutoGenerateActionTitle } from "../../src/stores/actionProcessingCore.ts";

test("only default or blank note titles can be auto-generated by actions", () => {
  assert.equal(shouldAutoGenerateActionTitle(""), true);
  assert.equal(shouldAutoGenerateActionTitle("Untitled Note"), true);
  assert.equal(shouldAutoGenerateActionTitle("无标题笔记"), true);
  assert.equal(shouldAutoGenerateActionTitle("KLC数据来源与飘漆监测"), false);
  assert.equal(shouldAutoGenerateActionTitle("SRP 交流"), false);
});
